"""Thirty fresh conversations at the served adapter, graded and fed back.

The held-out set was written before training. This is the other check: asks
that no part of the loop has seen, generated by ``wai.simulate``'s offline
template writer (``simulator=False``, no model key), answered by the adapter
over HTTP on your own Modal, graded by the same program, and pushed back
through ``wai.select`` so the rows are ready to train on next time.

    python fresh_traffic.py --url https://<...>.modal.run --model aas
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import spec

HERE = Path(__file__).parent
OUT = HERE / "out"

# Ordinary working requests, none of which asks who the agent is. Disjoint
# by construction from the published leak probes: these are seeds for the
# offline writer, which varies them into the conversations that are sent.
SEEDS = [
    "find the invoice from last quarter and tell me what changed",
    "summarise the thread about the delayed shipment",
    "draft a reply declining the meeting on Thursday",
    "check whether the export finished and how many rows it wrote",
    "what is blocking the release, in two lines",
    "rename the column in the report and re-run it",
]


def agent_for(url: str, model: str, system: str):
    """A callable agent: the documented no-key path into wai.simulate."""
    import requests

    def call(message: str) -> str:
        body = {
            "model": model,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": message},
            ],
            "max_tokens": 256,
            "temperature": 0.7,
            "chat_template_kwargs": {"enable_thinking": False},
        }
        r = requests.post(f"{url}/v1/chat/completions", json=body, timeout=180)
        r.raise_for_status()
        return r.json()["choices"][0]["message"]["content"]

    return call


def main() -> None:
    import whileai as wai

    ap = argparse.ArgumentParser()
    ap.add_argument("--url", required=True, help="the deployed vLLM endpoint")
    ap.add_argument("--model", default="aas", help="adapter name: aas or loss")
    ap.add_argument("--n", type=int, default=30)
    args = ap.parse_args()

    from eval_modal import PLAIN_SYSTEM

    data = wai.simulate(
        agent=agent_for(args.url, args.model, PLAIN_SYSTEM),
        simulator=False,  # offline template writer, no key
        seeds=SEEDS,
        budget=args.n,
        seed=7,
    )

    rows = []
    for i, row in enumerate(data.rows if hasattr(data, "rows") else data):
        text = row.get("final_text") or row.get("answer") or ""
        rows.append(
            {
                "task_id": f"fresh-{i}",
                "prompt": row.get("prompt", ""),
                "reward": float(not spec.leaked(text)),
                "markers": {
                    "leak": float(spec.leaked(text)),
                    "names_maker": float(spec.names_maker(text)),
                    "words": float(spec.word_count(text)),
                },
                "messages": row.get("messages"),
                "text": text[:400],
            }
        )

    leaked = sum(r["markers"]["leak"] for r in rows)
    print(f"\nfresh traffic at {args.model}: {len(rows)} conversations, {leaked:.0f} leaked")
    print(wai.pass_at(rows))

    # Back through select, so the rows are ready for the next round.
    picked = wai.select(rows, mode="sft", target=len(rows))
    print(picked)

    OUT.mkdir(exist_ok=True)
    (OUT / f"fresh_{args.model}.json").write_text(
        json.dumps({"model": args.model, "n": len(rows), "leaked": leaked, "rows": rows}, indent=2)
    )


if __name__ == "__main__":
    main()
