"""Generate the API reference pages under docs/api/ from the package itself.

One MDX page per public module group, one section per name in ``__all__``:
the signature as the interpreter sees it, then the docstring. The docs site
(Mintlify, reading docs/) renders them; ``--check`` fails when the committed
pages differ from what the installed package would produce, so a PR that
changes a public signature or docstring must regenerate them. Fix:

    uv run python scripts/gen_api_docs.py

then commit docs/api/ and docs/docs.json.
"""

from __future__ import annotations

import argparse
import difflib
import importlib
import inspect
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
API = DOCS / "api"
DOCS_JSON = DOCS / "docs.json"
ROOTS = ("whileai", "whileai.simulations")
GENERATED = (
    "{/* Generated by scripts/gen_api_docs.py from the package. Do not edit; fix the docstring. */}"
)
SOURCE_URL = "https://github.com/whilehq/whileai-sdk/blob/main"

# Groups that lead the sidebar; everything else follows alphabetically.
FIRST = ["whileai", "simulations", "data", "score", "generate", "world", "verify"]

GROUP_BLURB = {
    "whileai": "The platform client: sign in, tracked agents, runs, verdicts.",
    "simulations": "The top-level calls: simulate, grade, optimize, export, train.",
    "simulation": "simulate(): the entry point, and every argument it takes.",
    "data": "SimulationData: the object simulate() returns, and what it can do next.",
    "score": "Grading, judge checks, pass@k, selection for SFT and RL, hack scans.",
    "generate": "Situation writers, coverage axes, agent adapters, model backends.",
    "world": "The mock world that answers tool calls and fails on schedule.",
    "verify": "Verifiable rewards: programmatic checks a judge cannot game.",
    "run": "The search loop that spends the budget.",
    "ingest": "Local trace loading, OTLP rows, and the dataset calls.",
    "training": "Training runs, trainer callbacks, TRL export.",
    "export": "JSONL, preference pairs, and RL environments out of graded rows.",
    "environment": "A verifiers environment for on-policy trainers.",
    "openenv": "The OpenEnv runtime: reset, step and state over HTTP for TRL, torchforge and SkyRL.",
    "monitor": "Watch a live training run for reward hacking.",
    "schema": "The typed row schema and its conversions.",
    "constants": "Module-level constants and their defaults.",
}


def _module_of(obj: object) -> str | None:
    if inspect.ismodule(obj):
        return obj.__name__
    mod = getattr(obj, "__module__", None)
    return mod if isinstance(mod, str) else None


def _module_group(root: str, obj: object) -> str:
    if root == "whileai":
        return "whileai"
    mod = _module_of(obj)
    if mod is None or not mod.startswith("whileai.simulations"):
        return "constants"
    rest = mod[len("whileai.simulations") :].lstrip(".")
    return rest.split(".")[0] if rest else "simulations"


def _clean_signature(obj: object, name: str) -> str | None:
    if not callable(obj):
        return None
    try:
        sig = inspect.signature(obj)
    except (TypeError, ValueError):
        return None
    params = [str(p) for p in sig.parameters.values()]
    ret = ""
    if sig.return_annotation is not inspect.Signature.empty:
        ann = sig.return_annotation
        ret = " -> " + (ann if isinstance(ann, str) else inspect.formatannotation(ann))
    one = f"{name}({', '.join(params)}){ret}"
    if len(one) > 84 and params:
        body = "".join(f"    {p},\n" for p in params)
        one = f"{name}(\n{body}){ret}"
    one = re.sub(r" at 0x[0-9a-fA-F]+", "", one)
    one = re.sub(r"(: |-> )'([^']*)'", r"\1\2", one)
    return one


def _escape_prose(line: str) -> str:
    """Escape what MDX would read as JSX or an expression, outside inline code."""
    parts = re.split(r"(`[^`]*`)", line)
    for i in range(0, len(parts), 2):
        s = parts[i]
        s = s.replace("{", "\\{").replace("}", "\\}")
        s = re.sub(r"<(?=[A-Za-z/!])", "&lt;", s)
        parts[i] = s
    return "".join(parts)


def _prose(lines: list[str]) -> list[str]:
    """Render a run of prose: RST-style ``name`` (which may span a line
    break) becomes `name`, then each line gets the MDX escapes.

    Prose only. Run over the whole docstring, the collapse matched a
    fence's own backticks and turned ```python into ``python.
    """
    text = re.sub(r"``([^`]+)``", r"`\1`", "\n".join(lines))
    return [_escape_prose(line) for line in text.split("\n")]


def _docstring(obj: object) -> str:
    doc = inspect.getdoc(obj) or ""
    out: list[str] = []
    prose: list[str] = []
    in_fence = False
    in_doctest = False

    def flush() -> None:
        if prose:
            out.extend(_prose(prose))
            prose.clear()

    for line in doc.split("\n"):
        if line.startswith("```"):
            flush()
            in_fence = not in_fence
            out.append(line)
            continue
        if in_fence:
            out.append(line)
            continue
        is_doctest = line.lstrip().startswith(">>>") or (in_doctest and line.strip())
        if is_doctest and not in_doctest:
            flush()
            out.append("```python")
            in_doctest = True
        elif not is_doctest and in_doctest:
            out.append("```")
            in_doctest = False
        if in_doctest:
            out.append(line)
        else:
            prose.append(line)
    if in_doctest:
        out.append("```")
    flush()
    return "\n".join(out).strip()


def _first_sentence(doc: str) -> str:
    """The first sentence of a rendered docstring, on one line, for tables."""
    para = doc.split("\n\n")[0].replace("\n", " ").strip()
    # A period ends the sentence only before a capital, a backtick, a bracket
    # or the end, so "rlhf-book ch. 16" and "e.g. rows" do not cut it short.
    m = re.match(r"(.+?\.)(?=\s+[A-Z(`]|\s*$)", para)
    s = m.group(1) if m else para
    return s.replace("|", "\\|")


def _is_builtin_doc(obj: object) -> bool:
    """Constants inherit the docstring of their type; that is not documentation."""
    if inspect.isclass(obj):
        # A dataclass without a docstring gets its signature as one.
        return (inspect.getdoc(obj) or "").startswith(f"{obj.__name__}(")
    if inspect.isroutine(obj) or inspect.ismodule(obj):
        return False
    return inspect.getdoc(type(obj)) == inspect.getdoc(obj)


def _short_repr(obj: object) -> str:
    r = repr(obj)
    r = re.sub(r" at 0x[0-9a-fA-F]+", "", r)
    return r if len(r) <= 200 else r[:197] + "..."


def _source_path(obj: object) -> str | None:
    """The defining file, relative to the repo root, or None when it has none."""
    try:
        path = inspect.getsourcefile(obj)
    except (TypeError, OSError):
        return None
    if not path:
        return None
    # Slice from the package directory, so an editable checkout and a
    # site-packages install render the same link.
    parts = Path(path).parts
    if "whileai" not in parts:
        return None
    start = len(parts) - 1 - parts[::-1].index("whileai")
    return "/".join(parts[start:])


def _section(name: str, obj: object, level: str) -> str:
    parts = [f"{level} {name}", ""]
    if inspect.ismodule(obj):
        parts.append(f"Module `{obj.__name__}`.")
    else:
        sig = _clean_signature(obj, name.split(".")[-1])
        if sig is not None:
            if inspect.isclass(obj):
                sig = "class " + sig
            parts += ["```python", sig, "```"]
        elif not (inspect.isclass(obj) or callable(obj)):
            parts += ["```python", f"{name.split('.')[-1]} = {_short_repr(obj)}", "```"]
        # The file, not the line: a link that survives edits elsewhere in the module.
        src = _source_path(obj) if level == "###" and "." not in name else None
        if src:
            parts += ["", f"Defined in [`{src}`]({SOURCE_URL}/{src})."]
    doc = _docstring(obj)
    if doc and not _is_builtin_doc(obj):
        parts += ["", doc]
    if inspect.isclass(obj):
        for mname, member in sorted(vars(obj).items()):
            if mname.startswith("_") or not inspect.isfunction(member):
                continue
            if not inspect.getdoc(member):
                continue
            parts += ["", _section(f"{name}.{mname}", member, level + "#")]
    return "\n".join(parts)


def _submodule_intro(modname: str) -> str:
    try:
        mod = importlib.import_module(modname)
    except ImportError:
        return ""
    doc = _docstring(mod)
    return doc.split("\n\n")[0] if doc else ""


def _render_page(root: str, group: str, names: list[tuple[str, object]]) -> str:
    modname = root if group in ("whileai", "simulations") else f"{root}.{group}"
    blurb = GROUP_BLURB.get(group, f"Public names in {modname}.")
    alias = "wai" if root.endswith("simulations") else root
    head = [
        "---",
        f'title: "{modname}"',
        f'sidebarTitle: "{group}"',
        f'description: "{blurb}"',
        "---",
        "",
        GENERATED,
        "",
        f"{len(names)} public names. `import {root} as {alias}`, then `{alias}.name`."
        if alias == "wai"
        else f"{len(names)} public names. `import {root}`, then `{root}.name`.",
        "",
        "| Name | What it does |",
        "|---|---|",
    ]
    for name, obj in names:
        first = "" if _is_builtin_doc(obj) else _first_sentence(_docstring(obj))
        head.append(f"| [`{name}`](#{name.lower()}) | {first or '*no docstring*'} |")
    # One H2 per defining submodule, so a page with many names has structure.
    by_module: dict[str, list[tuple[str, object]]] = defaultdict(list)
    for name, obj in names:
        by_module[_module_of(obj) or modname].append((name, obj))
    body: list[str] = []
    multi = len(by_module) > 1
    for submod in sorted(by_module):
        if multi:
            short = submod[len(modname) :].lstrip(".") or "package"
            body += ["", f"## {short}", ""]
            intro = _submodule_intro(submod) if short != "package" else ""
            if intro:
                body += [intro, ""]
        for name, obj in by_module[submod]:
            body += ["", _section(name, obj, "###")]
    return "\n".join(head + body) + "\n"


def build() -> dict[str, str]:
    pages: dict[str, str] = {}
    groups: dict[tuple[str, str], list[tuple[str, object]]] = defaultdict(list)
    for root in ROOTS:
        mod = importlib.import_module(root)
        for name in sorted(getattr(mod, "__all__", ())):
            if name == "__version__":
                continue
            obj = getattr(mod, name)
            groups[(root, _module_group(root, obj))].append((name, obj))
    for (root, group), names in groups.items():
        pages[f"api/{group}.mdx"] = _render_page(root, group, names)
    by_group = {g: names for (_, g), names in groups.items()}
    order = [g for g in FIRST if g in by_group] + sorted(g for g in by_group if g not in FIRST)
    rows = "\n".join(
        f"| [{g}](/api/{g}) | {len(by_group[g])} | {GROUP_BLURB.get(g, '')} |" for g in order
    )
    pages["api/index.mdx"] = (
        "---\n"
        'title: "API reference"\n'
        'sidebarTitle: "Overview"\n'
        'description: "Every public name in whileai and whileai.simulations, with its signature and docstring, generated from the package."\n'
        "---\n\n"
        f"{GENERATED}\n\n"
        "These pages are generated from the installed package on every change, so a\n"
        "signature here is the signature the interpreter sees. Each name shows the\n"
        "signature with its defaults, the file that defines it, and its docstring.\n"
        "When to use which call, in the order a run happens, is on\n"
        "[the five calls](/reference/five-calls); every knob with its default is on\n"
        "[parameters](/reference/parameters); how a page is laid out is on\n"
        "[design](/reference/design).\n\n"
        "| Page | Names | What it holds |\n|---|---|---|\n"
        f"{rows}\n"
    )
    return pages


def nav_pages(pages: dict[str, str]) -> list[str]:
    groups = [p[len("api/") : -len(".mdx")] for p in pages if p != "api/index.mdx"]
    order = [g for g in FIRST if g in groups] + sorted(g for g in groups if g not in FIRST)
    return ["api/index"] + [f"api/{g}" for g in order]


def _find_api_group(node: object) -> dict | None:
    """The navigation group named "API", wherever docs.json nests it."""
    if isinstance(node, dict):
        if node.get("group") == "API" and "pages" in node:
            return node
        for v in node.values():
            found = _find_api_group(v)
            if found is not None:
                return found
    elif isinstance(node, list):
        for v in node:
            found = _find_api_group(v)
            if found is not None:
                return found
    return None


def updated_docs_json(pages: dict[str, str]) -> str:
    cfg = json.loads(DOCS_JSON.read_text(encoding="utf-8"))
    group = _find_api_group(cfg.get("navigation"))
    if group is None:
        raise SystemExit('docs/docs.json has no navigation group named "API"')
    group["pages"] = nav_pages(pages)
    return json.dumps(cfg, indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if docs/api/ is stale")
    args = ap.parse_args(argv)
    pages = build()
    pages["docs.json"] = updated_docs_json(pages)
    stale: list[str] = []
    for rel, text in pages.items():
        path = DOCS / rel
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(rel)
            if args.check:
                diff = difflib.unified_diff(
                    (current or "").splitlines(),
                    text.splitlines(),
                    f"committed {rel}",
                    "generated",
                    lineterm="",
                    n=1,
                )
                print("\n".join(list(diff)[:40]))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    extra = [p.name for p in API.glob("*.mdx") if f"api/{p.name}" not in pages]
    if args.check:
        if stale or extra:
            print(
                "docs/api/ is stale for:", ", ".join(stale + [f"api/{e} (remove)" for e in extra])
            )
            print(
                "Fix: uv run python scripts/gen_api_docs.py  # then commit docs/api/ and docs/docs.json"
            )
            return 1
        print(f"docs/api/ is current ({len(pages) - 1} pages)")
        return 0
    for e in extra:
        (API / e).unlink()
    print(f"wrote {len(stale)} file(s); {len(pages) - 1} pages under docs/api/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
