"""Generate the recipe pages under docs/recipes/ from recipes/**/README.md.

One page per recipe, plus an index per section. The recipe READMEs are the
source of truth: they are what a contributor writes and what CI smoke-tests,
so the site renders them rather than restating them. This script only
translates GitHub markdown into what Mintlify serves:

* the leading ``# H1`` moves into frontmatter, so the page has one title;
* relative links are resolved, recipe-to-recipe links become root doc paths
  (``/recipes/04-train/grpo``) and everything else an absolute GitHub URL,
  because a link to ``x.md`` breaks the site;
* bare ``<`` and ``{`` outside code become entities, since Mintlify parses
  these pages as MDX and would read them as JSX;
* an untagged code fence gets ``text``, so every block on the site has a
  language tag.

``--check`` fails when the committed pages differ from what the READMEs
would produce, so a PR that edits a recipe README regenerates them. Fix:

    uv run python scripts/gen_recipe_docs.py

then commit docs/recipes/ and docs/docs.json.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
RECIPES = ROOT / "recipes"
OUT = DOCS / "recipes"
DOCS_JSON = DOCS / "docs.json"
BLOB = "https://github.com/whilehq/whileai-sdk/blob/main"
TREE = "https://github.com/whilehq/whileai-sdk/tree/main"
IMAGE_SUFFIXES = {".png", ".svg", ".jpg", ".jpeg", ".gif", ".webp"}
# No "*/" anywhere in here: it would close the MDX comment early and the page
# would fail to parse ("Could not parse expression with acorn").
GENERATED = (
    "{/* Generated by scripts/gen_recipe_docs.py from the recipe READMEs."
    " Do not edit; fix the README in the recipe directory. */}"
)

# Directories that are contributor scaffolding, not recipes: they are full of
# <angle bracket> placeholders and teach nothing to a reader of the site.
SKIP_DIRS = {"_template"}

# The five steps of a run, in the order recipes/README.md tells you to read
# them, with the nav label for each.
STEPS = [
    ("01-simulate", "Simulate"),
    ("02-measure", "Measure"),
    ("03-select", "Select"),
    ("04-train", "Train"),
    ("05-export", "Export"),
]
SECTIONS = [("papers", "Papers"), ("community", "Community")]

STEP_BLURB = {
    "01-simulate": "Make rollouts: an agent, situations, a reward that is a program.",
    "02-measure": "Say what the numbers mean: pass@k, headroom, reward hacking, safety.",
    "03-select": "Turn graded rows into training data: SFT rows, pairs, RL groups.",
    "04-train": "Train it, hosted or on your own GPU, and watch the run page.",
    "05-export": "Ship the data and the adapter.",
}


# --------------------------------------------------------------------------
# Markdown, sliced into code and not-code
# --------------------------------------------------------------------------


def _split_fences(text: str) -> list[tuple[bool, str]]:
    """The text as (is_fenced_code, chunk) pairs, fences kept verbatim."""
    out: list[tuple[bool, str]] = []
    buf: list[str] = []
    fence: str | None = None
    for line in text.split("\n"):
        marker = re.match(r"^(\s*)(`{3,}|~{3,})", line)
        if fence is None and marker:
            if buf:
                out.append((False, "\n".join(buf)))
                buf = []
            fence = marker.group(2)[0] * 3
            buf.append(line)
        elif fence is not None and marker and marker.group(2).startswith(fence):
            buf.append(line)
            out.append((True, "\n".join(buf)))
            buf = []
            fence = None
        else:
            buf.append(line)
    if buf:
        out.append((fence is not None, "\n".join(buf)))
    return out


def _tag_fence(block: str) -> str:
    """An opening fence with no language gets ``text``."""
    lines = block.split("\n")
    head = re.match(r"^(\s*)(`{3,}|~{3,})\s*$", lines[0])
    if head:
        lines[0] = f"{head.group(1)}{head.group(2)}text"
    return "\n".join(lines)


def _map_prose(chunk: str, fn) -> str:
    """Apply ``fn`` to the chunk's prose, leaving inline code spans alone."""
    return "".join(
        part if i % 2 else fn(part) for i, part in enumerate(re.split(r"(`+[^`]*?`+)", chunk))
    )


def _escape_jsx(prose: str) -> str:
    """Mintlify parses .md as MDX, so a bare < or { is read as JSX and $...$ as math."""
    prose = re.sub(r"<(?![a-zA-Z/!][^<>]*>)", "&lt;", prose)
    # An angle-bracket placeholder or a bare tag-looking word is text, not JSX.
    prose = re.sub(r"<(?=[a-zA-Z_][a-zA-Z0-9_ -]*>)", "&lt;", prose)
    # Mintlify renders text between two dollar signs as LaTeX, so "$34 instead
    # of $91" became italic math. A recipe README never means math by "$".
    return prose.replace("{", "&#123;").replace("}", "&#125;").replace("$", "&#36;")


# --------------------------------------------------------------------------
# Links
# --------------------------------------------------------------------------


def _recipe_page(rel_path: str) -> str | None:
    """The doc path for a repo path that names a recipe directory, else None."""
    parts = rel_path.split("/")
    if not parts or parts[0] != "recipes":
        return None
    rest = parts[1:]
    if rest and rest[-1] == "README.md":
        rest = rest[:-1]
    if not rest:
        return "/recipes"
    if rest[0] in SKIP_DIRS or (len(rest) > 1 and rest[1] in SKIP_DIRS):
        return None
    if len(rest) == 1:
        # a section index (papers, community) or a bare step directory
        if rest[0] in dict(SECTIONS):
            return f"/recipes/{rest[0]}"
        return "/recipes" if rest[0] in dict(STEPS) else None
    if len(rest) == 2 and (RECIPES / rest[0] / rest[1]).is_dir():
        return f"/recipes/{rest[0]}/{rest[1]}"
    return None


def _doc_page(rel_path: str) -> str | None:
    """The root doc path for a link into docs/, else None if it has no page."""
    if not rel_path.startswith("docs/"):
        return None
    stem = re.sub(r"\.(md|mdx)$", "", rel_path[len("docs/") :])
    for candidate in (DOCS / f"{stem}.md", DOCS / f"{stem}.mdx"):
        if candidate.exists():
            return f"/{stem}"
    return None


def _rewrite_link(target: str, page_dir: Path, broken: list[str]) -> str:
    if target.startswith(("http://", "https://", "mailto:", "#", "/")):
        return target
    path, _, anchor = target.partition("#")
    anchor = f"#{anchor}" if anchor else ""
    if not path:
        return target
    resolved = (page_dir / path).resolve()
    try:
        rel = resolved.relative_to(ROOT).as_posix()
    except ValueError:
        broken.append(target)
        return target
    if not resolved.exists():
        broken.append(target)
        return f"{TREE}/{rel}{anchor}"
    if rel.startswith("docs/") and resolved.suffix.lower() in IMAGE_SUFFIXES:
        # A figure in docs/ is served by Mintlify from the docs root, so a
        # README can embed it by a path that also renders on GitHub.
        return "/" + rel[len("docs/") :]
    page = _recipe_page(rel) or _doc_page(rel)
    if page:
        return f"{page}{anchor}"
    base = TREE if resolved.is_dir() else BLOB
    return f"{base}/{rel}{anchor}"


def _rewrite_links(chunk: str, page_dir: Path, broken: list[str]) -> str:
    return re.sub(
        r"(\]\()([^)\s]+)(\))",
        lambda m: m.group(1) + _rewrite_link(m.group(2), page_dir, broken) + m.group(3),
        chunk,
    )


# --------------------------------------------------------------------------
# Pages
# --------------------------------------------------------------------------


def _first_paragraph(body: str) -> str:
    for chunk in body.split("\n\n"):
        text = chunk.strip()
        if not text or text.startswith(("#", "|", "```", ">")):
            continue
        text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
        # Backticks and emphasis go; an underscore stays, because it is part of
        # names like rubric_judge and pass_at that a description has to spell right.
        text = re.sub(r"[`*]", "", text).replace("\n", " ")
        return re.sub(r"\s+", " ", text).strip()
    return ""


def _one_sentence(text: str, limit: int = 220) -> str:
    # A full stop ends the sentence only when what follows starts one. Recipe
    # prose is full of "ch. 7", "et al." and "arXiv:2609.13866, September 2026",
    # and splitting on the first period cuts every one of them in half.
    match = re.search(r"[.!?](?=\s+([A-Z(\"']|https?://)|\s*$)", text)
    sentence = text[: match.end()] if match else text
    return sentence if len(sentence) <= limit else sentence[: limit - 1].rstrip() + "."


def _quote(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def convert(readme: Path, broken: list[str]) -> tuple[str, str, str]:
    """(title, description, body) for one README, translated for the site."""
    raw = readme.read_text(encoding="utf-8")
    heading = re.match(r"^#\s+(.+?)\s*$", raw, flags=re.M)
    title = heading.group(1) if heading and raw.startswith("#") else readme.parent.name
    body = raw[heading.end() :] if heading and raw.startswith("#") else raw
    description = _one_sentence(_first_paragraph(body))
    out: list[str] = []
    for is_code, chunk in _split_fences(body):
        if is_code:
            out.append(_tag_fence(chunk))
            continue
        chunk = re.sub(r"<!--.*?-->", "", chunk, flags=re.S)
        chunk = _rewrite_links(chunk, readme.parent, broken)
        out.append(_map_prose(chunk, _escape_jsx))
    return title, description, "\n".join(out).strip()


def _page(title: str, sidebar: str, description: str, source: Path, body: str) -> str:
    rel = source.parent.relative_to(ROOT).as_posix()
    head = [
        "---",
        f'title: "{_quote(title)}"',
        f'sidebarTitle: "{_quote(sidebar)}"',
    ]
    if description:
        head.append(f'description: "{_quote(description)}"')
    head += [
        "---",
        "",
        GENERATED,
        "",
        "<Note>The scripts are in the repository, not in the installed package. Clone it,",
        f"then `cd {rel}` before running the commands below. "
        f"[Browse this recipe on GitHub]({TREE}/{rel}).</Note>",
        "",
        body,
        "",
    ]
    return "\n".join(head)


def _index_cards(entries: list[tuple[str, str, str]]) -> list[str]:
    """A CardGroup over (href, title, blurb)."""
    lines = ["<CardGroup cols={2}>"]
    for href, title, blurb in entries:
        lines.append(f'  <Card title="{_quote(title)}" href="{href}">')
        lines.append(f"    {blurb}")
        lines.append("  </Card>")
    lines.append("</CardGroup>")
    return lines


def _step_table_blurbs() -> dict[str, str]:
    """The "What you learn" cell for each recipe, from recipes/README.md."""
    text = (RECIPES / "README.md").read_text(encoding="utf-8")
    blurbs: dict[str, str] = {}
    for row in re.finditer(r"^\|\s*\[`([^`]+)`\]\(([^)]+)\)\s*\|([^|]*)\|", text, flags=re.M):
        blurbs[row.group(2).strip("/")] = row.group(3).strip()
    return blurbs


def _recipe_dirs(parent: Path) -> list[Path]:
    return sorted(
        d
        for d in parent.iterdir()
        if d.is_dir() and d.name not in SKIP_DIRS and (d / "README.md").exists()
    )


def build() -> tuple[dict[str, str], list[str], list[str]]:
    pages: dict[str, str] = {}
    broken: list[str] = []
    unlisted: list[str] = []
    blurbs = _step_table_blurbs()

    def emit(readme: Path, out_rel: str, sidebar: str) -> tuple[str, str]:
        title, description, body = convert(readme, broken)
        pages[out_rel] = _page(title, sidebar, description, readme, body)
        return title, description

    index_sections: list[tuple[str, str, list[tuple[str, str, str]]]] = []

    for step, label in STEPS:
        entries: list[tuple[str, str, str]] = []
        for d in _recipe_dirs(RECIPES / step):
            key = f"{step}/{d.name}"
            _, description = emit(d / "README.md", f"recipes/{key}.mdx", d.name)
            blurb = blurbs.get(key)
            if blurb is None:
                unlisted.append(key)
                blurb = description
            entries.append((f"/recipes/{key}", d.name, _map_prose(blurb, _escape_jsx)))
        if entries:
            index_sections.append((label, STEP_BLURB.get(step, ""), entries))

    for section, label in SECTIONS:
        readme = RECIPES / section / "README.md"
        title, description, body = convert(readme, broken)
        entries = []
        for d in _recipe_dirs(RECIPES / section):
            key = f"{section}/{d.name}"
            _, rdescription = emit(d / "README.md", f"recipes/{key}.mdx", d.name)
            entries.append((f"/recipes/{key}", d.name, _map_prose(rdescription, _escape_jsx)))
        cards = _index_cards(entries) if entries else []
        pages[f"recipes/{section}/index.mdx"] = _page(
            title, "Overview", description, readme, body + "\n\n" + "\n".join(cards)
        )
        index_sections.append((label, _one_sentence(description), entries))

    pages["recipes/index.mdx"] = _render_index(index_sections)
    return pages, broken, sorted(unlisted)


def _render_index(sections: list[tuple[str, str, list[tuple[str, str, str]]]]) -> str:
    total = sum(len(entries) for _, _, entries in sections)
    lines = [
        "---",
        'title: "Recipes"',
        'sidebarTitle: "Overview"',
        'description: "One post-training run as five steps, each step a runnable, '
        'self-contained recipe: what you learn, what you need, how long it takes."',
        "---",
        "",
        GENERATED,
        "",
        f"{total} runnable recipes, one directory each. Every recipe says what you",
        "learn, what it needs and how long it takes, and its first command runs the",
        "whole thing. Anything marked offline needs no key and no network.",
        "",
        "Read them in order the first time. After that, jump to the step you are on.",
        "",
        "<Note>",
        "  The scripts live in the repository, not in the installed package. Clone it",
        f"  first: `git clone {TREE.rsplit('/tree/', 1)[0]}.git`, then `cd` to the recipe",
        "  directory named at the top of its page.",
        "</Note>",
        "",
    ]
    for label, blurb, entries in sections:
        lines += [f"## {label}", ""]
        if blurb:
            lines += [_map_prose(blurb, _escape_jsx), ""]
        lines += [*_index_cards(entries), ""]
    lines += [
        "## Write one",
        "",
        f"Copy [`recipes/_template`]({TREE}/recipes/_template) into the step it belongs",
        "to, replace the parts in angle brackets, and open a pull request. The contract is in",
        f"[CONTRIBUTING.md]({BLOB}/CONTRIBUTING.md#contributing-a-recipe).",
        "",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------
# docs.json
# --------------------------------------------------------------------------


def _nav_groups(pages: dict[str, str]) -> list[dict]:
    groups: list[dict] = []
    for step, label in STEPS:
        nav = sorted(p[: -len(".mdx")] for p in pages if p.startswith(f"recipes/{step}/"))
        if nav:
            groups.append({"group": label, "pages": nav})
    for section, label in SECTIONS:
        nav = [
            f"recipes/{section}/index",
            *sorted(
                p[: -len(".mdx")]
                for p in pages
                if p.startswith(f"recipes/{section}/") and p != f"recipes/{section}/index.mdx"
            ),
        ]
        groups.append({"group": label, "pages": nav})
    return [{"group": "Recipes", "pages": ["recipes/index", *groups]}]


def _library_tab(cfg: dict) -> dict:
    for tab in cfg.get("navigation", {}).get("tabs", []):
        if tab.get("tab") == "Library":
            return tab
    raise SystemExit('docs/docs.json has no navigation tab named "Library"')


def updated_docs_json(pages: dict[str, str]) -> str:
    cfg = json.loads(DOCS_JSON.read_text(encoding="utf-8"))
    tab = _library_tab(cfg)
    groups = [g for g in tab["groups"] if g.get("group") != "Recipes"]
    new = _nav_groups(pages)[0]
    # Recipes sit after the guides that teach the calls, before the reference.
    at = next((i for i, g in enumerate(groups) if g.get("group") == "Reference"), len(groups))
    tab["groups"] = [*groups[:at], new, *groups[at:]]
    return json.dumps(cfg, indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if docs/recipes/ is stale")
    args = ap.parse_args(argv)
    pages, broken, unlisted = build()
    n_recipes = len(pages) - 3
    pages["docs.json"] = updated_docs_json(pages)

    stale: list[str] = []
    for rel, text in sorted(pages.items()):
        path = DOCS / rel
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        stale.append(rel)
        if args.check:
            diff = difflib.unified_diff(
                (current or "").splitlines(),
                text.splitlines(),
                f"committed {rel}",
                "generated",
                lineterm="",
                n=1,
            )
            print("\n".join(list(diff)[:40]))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")

    extra = [
        p.relative_to(DOCS).as_posix()
        for p in OUT.rglob("*")
        if p.is_file() and p.relative_to(DOCS).as_posix() not in pages
    ]
    if broken:
        print("recipe README links that do not resolve:", ", ".join(sorted(set(broken))))
    if unlisted:
        print("recipes with no row in recipes/README.md:", ", ".join(unlisted))

    if args.check:
        if stale or extra:
            print(
                "docs/recipes/ is stale for:",
                ", ".join(stale + [f"{e} (remove)" for e in extra]),
            )
            print(
                "Fix: uv run python scripts/gen_recipe_docs.py"
                "  # then commit docs/recipes/ and docs/docs.json"
            )
            return 1
        print(f"docs/recipes/ is current ({n_recipes} recipes)")
        return 0
    for e in extra:
        (DOCS / e).unlink()
    print(f"wrote {len(stale)} file(s); {n_recipes} recipes under docs/recipes/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
